- id: primary-oss_ldap
  type: group
  role: [primary-oss_ldap]
  tasks: &common_tasks
    - hiera
    - setup_repositories
    - fuel_pkgs
    - globals
    - tools
    - logging
    - netconfig
    - hosts
    - cluster-haproxy
  required_for: [deploy_end]
  requires: [deploy_start]
  parameters:
    strategy:
      type: one_by_one

- id: oss_ldap
  type: group
  role: [oss_ldap]
  tasks: *common_tasks
  required_for: [deploy_end]
  requires: [deploy_start, primary-oss_ldap]
  parameters:
    strategy:
      type: parallel


- id: oss_ldap-ldap_hosts
  type: puppet
  groups: [primary-oss_ldap, oss_ldap]
  required_for: [deploy_end]
  requires: [cluster-haproxy]
  parameters:
    puppet_manifest: "puppet/manifests/ldap_hosts.pp"
    puppet_modules: "puppet/modules:/etc/puppet/modules"
    timeout: 120
  reexecute_on:
    - deploy_changes

- id: oss_ldap-hiera
  type: puppet
  groups: [primary-oss_ldap, oss_ldap]
  requires: [globals]
  required_for: [logging, oss_ldap-cluster, oss_ldap-haproxy]
  parameters:
    puppet_manifest: "puppet/manifests/hiera_override.pp"
    puppet_modules: "puppet/modules:/etc/puppet/modules"
    timeout: 120
  reexecute_on:
    - deploy_changes


- id: oss_ldap-firewall
  type: puppet
  groups: [primary-oss_ldap, oss_ldap]
  required_for: [deploy_end]
  requires: [netconfig]
  parameters:
    puppet_manifest: "puppet/manifests/firewall.pp"
    puppet_modules: "puppet/modules:/etc/puppet/modules"
    timeout: 3600


- id: oss_ldap-cluster
  type: puppet
  groups: [primary-oss_ldap, oss_ldap]
  required_for: [cluster-haproxy]
  requires: [oss_ldap-firewall]
  parameters:
    puppet_manifest: "puppet/manifests/cluster.pp"
    puppet_modules: "puppet/modules:/etc/puppet/modules"
    timeout: 3600
  reexecute_on:
    - deploy_changes


- id: oss_ldap-virtual-ip
  type: puppet
  groups: [primary-oss_ldap, oss_ldap]
  required_for: [deploy_end]
  requires: [oss_ldap-cluster]
  parameters:
    puppet_manifest: "/etc/puppet/modules/osnailyfacter/modular/virtual_ips/virtual_ips.pp"
    puppet_modules: "puppet/modules:/etc/puppet/modules"
    timeout: 3600


# This task needs to be reexecuted to reconfigure HAProxy backends
- id: oss_ldap-haproxy
  type: puppet
  groups: [primary-oss_ldap, oss_ldap]
  requires: [cluster-haproxy, oss_ldap-virtual-ip]
  required_for: [deploy_end]
  parameters:
    puppet_manifest: "puppet/manifests/haproxy.pp"
    puppet_modules: "puppet/modules:/etc/puppet/modules"
    timeout: 120
  reexecute_on:
    - deploy_changes


- id: oss_ldap-provision-services
  type: puppet
  role: [primary-oss_ldap]
  requires: [post_deployment_start]
  required_for: [oss_ldap-enable-quorum, post_deployment_end]
  parameters:
    puppet_manifest: puppet/manifests/provision_services.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 600
  reexecute_on:
    - deploy_changes


- id: oss_ldap-enable-quorum
  type: puppet
  role: [primary-oss_ldap]
  requires: [post_deployment_start]
  required_for: [post_deployment_end]
  parameters:
    puppet_manifest: "puppet/manifests/enable_quorum.pp"
    puppet_modules: "puppet/modules:/etc/puppet/modules"
    timeout: 120
  reexecute_on:
    - deploy_changes



















##############
- id: oss_ldap-101_install_openldap_server
  type: puppet
  role: [primary-oss_ldap, oss_ldap]
  requires: [oss_ldap-enable-quorum,post_deployment_start]
  required_for: [post_deployment_end]
  parameters:
    puppet_manifest: "puppet/manifests/101_install_openldap_server.pp"
    puppet_modules: "puppet/modules:/etc/puppet/modules"
    timeout: 120
  reexecute_on:
    - deploy_changes



- id: oss_ldap-102_configure_replica_objects
  type: puppet
  role: [primary-oss_ldap, oss_ldap]
  requires: [oss_ldap-101_install_openldap_server]
  required_for: [post_deployment_end]
  parameters:
    puppet_manifest: "puppet/manifests/102_configure_replica_objects.pp"
    puppet_modules: "puppet/modules:/etc/puppet/modules"
    timeout: 120
  reexecute_on:
    - deploy_changes


- id: oss_ldap-103_populate_ldap_customers_organization
  type: puppet
  role: [primary-oss_ldap, oss_ldap]
  requires: [oss_ldap-102_configure_replica_objects]
  required_for: [post_deployment_end]
  parameters:
    puppet_manifest: "puppet/manifests/103_populate_ldap_customers_organization.pp"
    puppet_modules: "puppet/modules:/etc/puppet/modules"
    timeout: 120
  reexecute_on:
    - deploy_changes


- id: oss_ldap-104_populate_ldap_people_ou
  type: puppet
  role: [primary-oss_ldap, oss_ldap]
  requires: [oss_ldap-103_populate_ldap_customers_organization]
  required_for: [post_deployment_end]
  parameters:
    puppet_manifest: "puppet/manifests/104_populate_ldap_people_ou.pp"
    puppet_modules: "puppet/modules:/etc/puppet/modules"
    timeout: 120
  reexecute_on:
    - deploy_changes

- id: oss_ldap-110_configure_replica_objects
  type: puppet
  role: [primary-oss_ldap, oss_ldap]
  requires: [oss_ldap-104_populate_ldap_people_ou]
  required_for: [post_deployment_end]
  parameters:
    puppet_manifest: "puppet/manifests/110_configure_replica_objects.pp"
    puppet_modules: "puppet/modules:/etc/puppet/modules"
    timeout: 120
  reexecute_on:
    - deploy_changes



- id: oss_ldap-120_phpldapadmin
  type: puppet
  role: [primary-oss_ldap, oss_ldap]
  requires: [oss_ldap-110_configure_replica_objects]
  required_for: [post_deployment_end]
  parameters:
    puppet_manifest: "puppet/manifests/120_phpldapadmin.pp"
    puppet_modules: "puppet/modules:/etc/puppet/modules"
    timeout: 120
  reexecute_on:
    - deploy_changes


- id: oss_ldap-140_populate_ldap_customers_organization
  type: puppet
  role: [primary-oss_ldap]
  requires: [oss_ldap-120_phpldapadmin]
  required_for: [post_deployment_end]
  parameters:
    puppet_manifest: "puppet/manifests/140_populate_ldap_customers_organization.pp"
    puppet_modules: "puppet/modules:/etc/puppet/modules"
    timeout: 120
  reexecute_on:
    - deploy_changes



- id: oss_ldap-150_populate_ldap_people_ou
  type: puppet
  role: [primary-oss_ldap]
  requires: [oss_ldap-140_populate_ldap_customers_organization]
  required_for: [post_deployment_end]
  parameters:
    puppet_manifest: "puppet/manifests/150_populate_ldap_people_ou.pp"
    puppet_modules: "puppet/modules:/etc/puppet/modules"
    timeout: 120
  reexecute_on:
    - deploy_changes



- id: oss_ldap-160_sudo_scheme
  type: puppet
  role: [primary-oss_ldap]
  requires: [oss_ldap-150_populate_ldap_people_ou]
  required_for: [post_deployment_end]
  parameters:
    puppet_manifest: "puppet/manifests/160_sudo_scheme.pp"
    puppet_modules: "puppet/modules:/etc/puppet/modules"
    timeout: 120
  reexecute_on:
    - deploy_changes



- id: oss_ldap-165_populate_ldap_sudo_ou
  type: puppet
  role: [primary-oss_ldap]
  requires: [oss_ldap-160_sudo_scheme]
  required_for: [post_deployment_end]
  parameters:
    puppet_manifest: "puppet/manifests/165_populate_ldap_sudo_ou.pp"
    puppet_modules: "puppet/modules:/etc/puppet/modules"
    timeout: 120
  reexecute_on:
    - deploy_changes



- id: oss_ldap-166
  type: puppet
  role: [primary-oss_ldap]
  requires: [oss_ldap-165_populate_ldap_sudo_ou]
  required_for: [post_deployment_end]
  parameters:
    puppet_manifest: "puppet/manifests/166.pp"
    puppet_modules: "puppet/modules:/etc/puppet/modules"
    timeout: 120
  reexecute_on:
    - deploy_changes



- id: oss_ldap-167
  type: puppet
  role: [primary-oss_ldap]
  requires: [oss_ldap-166]
  required_for: [post_deployment_end]
  parameters:
    puppet_manifest: "puppet/manifests/167.pp"
    puppet_modules: "puppet/modules:/etc/puppet/modules"
    timeout: 120
  reexecute_on:
    - deploy_changes







- id: oss_ldap-170
  type: puppet
  role: [primary-oss_ldap]
  requires: [oss_ldap-167]
  required_for: [post_deployment_end]
  parameters:
    puppet_manifest: "puppet/manifests/170.pp"
    puppet_modules: "puppet/modules:/etc/puppet/modules"
    timeout: 120
  reexecute_on:
    - deploy_changes





- id: oss_ldap-171
  type: puppet
  role: [primary-oss_ldap]
  requires: [oss_ldap-170]
  required_for: [post_deployment_end]
  parameters:
    puppet_manifest: "puppet/manifests/171.pp"
    puppet_modules: "puppet/modules:/etc/puppet/modules"
    timeout: 120
  reexecute_on:
    - deploy_changes





- id: oss_ldap-172
  type: puppet
  role: [primary-oss_ldap]
  requires: [oss_ldap-171]
  required_for: [post_deployment_end]
  parameters:
    puppet_manifest: "puppet/manifests/172.pp"
    puppet_modules: "puppet/modules:/etc/puppet/modules"
    timeout: 120
  reexecute_on:
    - deploy_changes




- id: oss_ldap-173
  type: puppet
  role: [primary-oss_ldap]
  requires: [oss_ldap-172]
  required_for: [post_deployment_end]
  parameters:
    puppet_manifest: "puppet/manifests/173.pp"
    puppet_modules: "puppet/modules:/etc/puppet/modules"
    timeout: 120
  reexecute_on:
    - deploy_changes



- id: oss_ldap-174
  type: puppet
  role: [primary-oss_ldap]
  requires: [oss_ldap-173]
  required_for: [post_deployment_end]
  parameters:
    puppet_manifest: "puppet/manifests/174.pp"
    puppet_modules: "puppet/modules:/etc/puppet/modules"
    timeout: 120
  reexecute_on:
    - deploy_changes





- id: oss_ldap-180
  type: puppet
  role: [primary-oss_ldap]
  requires: [oss_ldap-174]
  required_for: [post_deployment_end]
  parameters:
    puppet_manifest: "puppet/manifests/180.pp"
    puppet_modules: "puppet/modules:/etc/puppet/modules"
    timeout: 120
  reexecute_on:
    - deploy_changes




- id: oss_ldap-181
  type: puppet
  role: [primary-oss_ldap]
  requires: [oss_ldap-180]
  required_for: [post_deployment_end]
  parameters:
    puppet_manifest: "puppet/manifests/181.pp"
    puppet_modules: "puppet/modules:/etc/puppet/modules"
    timeout: 120
  reexecute_on:
    - deploy_changes





- id: oss_ldap-182
  type: puppet
  role: [primary-oss_ldap]
  requires: [oss_ldap-181]
  required_for: [post_deployment_end]
  parameters:
    puppet_manifest: "puppet/manifests/182.pp"
    puppet_modules: "puppet/modules:/etc/puppet/modules"
    timeout: 120
  reexecute_on:
    - deploy_changes




- id: oss_ldap-183
  type: puppet
  role: [primary-oss_ldap]
  requires: [oss_ldap-182]
  required_for: [post_deployment_end]
  parameters:
    puppet_manifest: "puppet/manifests/183.pp"
    puppet_modules: "puppet/modules:/etc/puppet/modules"
    timeout: 120
  reexecute_on:
    - deploy_changes




- id: oss_ldap-185
  type: puppet
  role: [primary-oss_ldap]
  requires: [oss_ldap-183]
  required_for: [post_deployment_end]
  parameters:
    puppet_manifest: "puppet/manifests/185.pp"
    puppet_modules: "puppet/modules:/etc/puppet/modules"
    timeout: 120
  reexecute_on:
    - deploy_changes



- id: oss_ldap-190
  type: puppet
  role: [primary-oss_ldap]
  requires: [oss_ldap-185]
  required_for: [post_deployment_end]
  parameters:
    puppet_manifest: "puppet/manifests/190.pp"
    puppet_modules: "puppet/modules:/etc/puppet/modules"
    timeout: 120
  reexecute_on:
    - deploy_changes




- id: oss_ldap-193
  type: puppet
  role: [primary-oss_ldap]
  requires: [oss_ldap-190]
  required_for: [post_deployment_end]
  parameters:
    puppet_manifest: "puppet/manifests/193.pp"
    puppet_modules: "puppet/modules:/etc/puppet/modules"
    timeout: 120
  reexecute_on:
    - deploy_changes


- id: oss_ldap-200
  type: puppet
  role: [primary-oss_ldap]
  requires: [oss_ldap-193]
  required_for: [post_deployment_end]
  parameters:
    puppet_manifest: "puppet/manifests/200.pp"
    puppet_modules: "puppet/modules:/etc/puppet/modules"
    timeout: 120
  reexecute_on:
    - deploy_changes



- id: oss_ldap-900
  type: puppet
  role: [primary-oss_ldap,oss_ldap]
  requires: [oss_ldap-110_configure_replica_objects]
  required_for: [post_deployment_end]
  parameters:
    puppet_manifest: "puppet/manifests/185.pp"
    puppet_modules: "puppet/modules:/etc/puppet/modules"
    timeout: 120
  reexecute_on:
    - deploy_changes










