- id: primary-oss_ldap
  type: group
  role: [primary-oss_ldap]
  tasks: &common_tasks
    - hiera
    - setup_repositories
    - fuel_pkgs
    - globals
    - tools
    - logging
    - netconfig
    - hosts
    - cluster-haproxy
  required_for: [deploy_end]
  requires: [deploy_start]
  parameters:
    strategy:
      type: one_by_one

- id: oss_ldap
  type: group
  role: [oss_ldap]
  tasks: *common_tasks
  required_for: [deploy_end]
  requires: [deploy_start, primary-oss_ldap]
  parameters:
    strategy:
      type: parallel

- id: oss_ldap-enable-quorum
  type: puppet
  role: [primary-oss_ldap]
  requires: [post_deployment_start]
  required_for: [post_deployment_end]
  parameters:
    puppet_manifest: "puppet/manifests/enable_quorum.pp"
    puppet_modules: "puppet/modules"
    timeout: 120
  reexecute_on:
    - deploy_changes

# This task needs to be reexecuted to adapt configuration variables depending
# on the number of nodes in the cluster
- id: oss_ldap-hiera
  type: puppet
  groups: [primary-oss_ldap, oss_ldap]
  requires: [globals]
  required_for: [logging, oss_ldap-cluster, oss_ldap-haproxy]
  parameters:
    puppet_manifest: "puppet/manifests/hiera_override.pp"
    puppet_modules: "puppet/modules"
    timeout: 120
  reexecute_on:
    - deploy_changes


- id: oss_ldap-firewall
  type: puppet
  groups: [primary-oss_ldap, oss_ldap]
  required_for: [deploy_end]
  requires: [netconfig]
  parameters:
    puppet_manifest: "puppet/manifests/firewall.pp"
    puppet_modules: "puppet/modules"
    timeout: 3600


- id: oss_ldap-cluster
  type: puppet
  groups: [primary-oss_ldap, oss_ldap]
  required_for: [cluster-haproxy]
  requires: [oss_ldap-firewall]
  parameters:
    puppet_manifest: "puppet/manifests/cluster.pp"
    puppet_modules: "puppet/modules"
    timeout: 3600
  reexecute_on:
    - deploy_changes



# This task needs to be reexecuted to reconfigure HAProxy backends
- id: oss_ldap-haproxy
  type: puppet
  groups: [primary-oss_ldap, oss_ldap]
  requires: [cluster-haproxy, oss_ldap-virtual-ip]
  required_for: [deploy_end]
  parameters:
    puppet_manifest: "puppet/manifests/haproxy.pp"
    puppet_modules: "puppet/modules"
    timeout: 120
  reexecute_on:
    - deploy_changes




- id: oss_ldap-virtual-ip
  type: puppet
  groups: [primary-oss_ldap, oss_ldap]
  required_for: [deploy_end]
  requires: [oss_ldap-cluster]
  parameters:
    puppet_manifest: "puppet/modules/osnailyfacter/modular/virtual_ips/virtual_ips.pp"
    puppet_modules: "puppet/modules"
    timeout: 3600
